### PR TITLE
support v1 or v2 sync

### PR DESCRIPTION
**Pull request by otakup0pe**
This seems to have gotten me up and running with V2. I was not, however, able to automagically configure the device/folders.

### CODE REVIEW

**Comment by francois2metz** [comment]
We might choose to support only the v2.

**Comment by otakup0pe** [comment]
That's the direction _I_ am going as well. Do you want me to change the PR to only support v2?

**Comment by francois2metz** [comment]
yes please. Thanks :scissors:

**Comment by otakup0pe** [comment]
Better late than never, eh ?

**Comment by francois2metz** [comment]
Thanks! Merge manually.

**Comment by francois2metz** [comment]
:green_heart: :heart: :purple_heart:

**Pull request closed without merging**
